config/routes.rb
Cookbook::Application.routes.draw do
  resources :sessions, :only => [:new, :create]
  match "logout" => "sessions#destroy", :as => "logout"
  match "login" => "sessions#new", :as => "login"

  resources :users, :only => [:new, :create]


  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  resources :ingredients

  resources :comments

  resources :steps

  resources :categories

  get "recipes/index"

  get "recipes/new"
  post "recipes/create"

  get "recipes/edit/:id" => "recipes#edit", :as => :edit_recipe
  put "recipes/update:id" => 'recipes#update', :as => :update_recipe

  delete "recipes/destroy/:id" => 'recipes#destroy', :as => :delete_recipe

  get "recipes/:id" => "recipes#show", :as => :recipe

  root :to => 'recipes#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :content, :title
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(params[:recipe])
      if @recipe.save
        redirect_to "/recipes/index"
      else
        render :new
      end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(params[:recipe])
      redirect_to "/recipes/index"
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.delete
    redirect_to "/recipes/index"
  end

  def show
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/create.html.erb
<h1>Recipes#create</h1>
<p>Find me in app/views/recipes/create.html.erb</p>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/edit.html.erb
<h1>Recipes#edit</h1>
<p>Find me in app/views/recipes/edit.html.erb</p>

<%= form_for @recipe, :url => {:action => "update"} do |f| %>
  <label>Title</label>
  <%= f.text_field :title %>
  <label>Content</label>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/recipes/index.html.erb
<h1>Recipes#index</h1>
<p>Find me in app/views/recipes/index.html.erb</p>

<% @recipes.each do |recipe| %>
  <ul>
    <li>
      <%= link_to recipe.title, recipe_path(recipe.id) %> |
      <%= link_to "Edit", edit_recipe_path(recipe.id) %> |
      <%= link_to "Delete", delete_recipe_path(recipe.id), :method => :delete %>
    </li>
  </ul>
<% end %>

app/views/recipes/new.html.erb
<h1>Recipes#new</h1>
<p>Find me in app/views/recipes/new.html.erb</p>

<%= form_for @recipe, :url => {:action => "create"} do |f| %>
  <label>Title</label><br>
  <%= f.text_field :title %>
  <br>
  <label>Content</label>
  <%= f.text_area :content %>
  <br>
  <%= f.submit %>
<% end %>

app/views/recipes/show.html.erb
<h1>Recipes#show</h1>
<p>Find me in app/views/recipes/show.html.erb</p>

<h3><%= @recipe.title %></h3>
<p><%= @recipe.content %></p>

app/views/recipes/update.html.erb
<h1>Recipes#update</h1>
<p>Find me in app/views/recipes/update.html.erb</p>